[package]
name = "psr_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
egui = "0.21.0"
eframe = "0.21.3"
image = "0.24.4"
